USE [master]
GO

/****** Object:  Database [QuanLySieuThi]    Script Date: 12/5/2016 9:30:32 AM ******/
CREATE DATABASE [QuanLySieuThi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLySieuThi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QuanLySieuThi.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QuanLySieuThi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QuanLySieuThi_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QuanLySieuThi] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLySieuThi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLySieuThi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLySieuThi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLySieuThi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuanLySieuThi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLySieuThi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLySieuThi] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLySieuThi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLySieuThi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLySieuThi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLySieuThi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QuanLySieuThi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLySieuThi] SET  READ_WRITE 
GO

