//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTonKhoView
    {
        public int MaBaoCaoTonKho { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public string TenHangHoa { get; set; }
        public Nullable<int> SoLuongDauKy { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<int> SoLuongCuoiKy { get; set; }
    }
}
