//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonThanhToan
    {
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string HoTen { get; set; }
        public string HoTenKhachHang { get; set; }
        public string TenHangHoa { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> TienGiam { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
